# Site settings
title: ossia score
email: ossia.collective@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open software system for interactive applications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

