# Site settings
title: ossia | home of ossia score and libossia
email: contact@ossia.io
description: > # this means to ignore newlines until "baseurl:"
  Open Software System for Interactive Applications - home of ossia score, a free, open-source, cross-platform intermedia sequencer for precise and flexible scripting of interactive scenarios.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://ossia.io" # the base hostname & protocol for your site
image: "/assets/score-logo.png"
include: ["_pages"]
permalink: /posts/:title/
# Build settings
markdown: kramdown
collections:
  score_features:
    output: true
  libossia_features:
    output: true

