# Site settings
title: ossia
email: ossia.collective@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Open software system for interactive applications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll
image: "/assets/score-logo.png"
include: ["_pages"]
permalink: /posts/:title/
# Build settings
markdown: kramdown
collections:
  score_features:
    output: true

